/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
  alt?: string;
  caption?: string;
}

export interface Pages {
  id: string;
  title: string;
  slug: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: Media | string;
  };
  layout?: Array<
    | {
        blockType: "hero";
        heading: string;
        subheading?: string;
        heroType?: "split" | "centered" | "full";
        image?: Media | string;
        ctaLabel?: string;
        ctaLink?: string;
      }
    | {
        blockType: "richContent";
        content: string;
      }
    | {
        blockType: "imageGallery";
        title?: string;
        images?: Array<{
          image?: Media | string;
          caption?: string;
        }>;
        columns?: "2" | "3" | "4";
      }
    | {
        blockType: "callToAction";
        heading: string;
        description?: string;
        buttonLabel?: string;
        buttonLink?: string;
        theme?: "primary" | "secondary" | "dark";
      }
    | {
        blockType: "testimonial";
        heading: string;
        subheading: string;
        testimonials?: Array<{
          name: string;
          position: string;
          avatar?: Media | string;
          quote: string;
        }>;
      }
  >;
  createdAt: string;
  updatedAt: string;
}

export interface Posts {
  id: string;
  title: string;
  slug: string;
  excerpt?: string;
  content?: string;
  image?: Media | string;
  publishedAt?: string;
  status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
}

export interface Inquiries {
  id: string;
  name: string;
  email: string;
  type?: "prayer" | "general";
  message: string;
  createdAt: string;
  updatedAt: string;
}

export interface Comments {
  id: string;
  author: string;
  text: string;
  postSlug: string;
  createdAt: string;
  updatedAt: string;
}

export interface NavigationGlobal {
  menuItems?: Array<{
    label?: string;
    url?: string;
    page?: Pages | string;
    openInNewTab?: boolean;
  }>;
}

export interface SettingsGlobal {
  siteName?: string;
  tagline?: string;
  logo?: Media | string;
  homePage?: Pages | string;
  footerText?: string;
}

export interface DyrectedSchema {
  collections: {
    media: Media;
    pages: Pages;
    posts: Posts;
    inquiries: Inquiries;
    comments: Comments;
  };
  globals: {
    navigation: NavigationGlobal;
    settings: SettingsGlobal;
  };
}
