/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
  alt?: string;
}

// URL field types
export type UrlFieldValue =
  | {
      type: "custom";
      url: string;
      label?: string;
    }
  | {
      type: "internal";
      url: string;
      relationTo: string;
      value: string;
      label?: string;
    };

// Backward compatibility for simple string URLs
export type UrlField = UrlFieldValue | string;

export interface Pages {
  id: string;
  title: string;
  slug: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: Media | string;
  };
  layout?: Array<
    | {
        blockType: "hero";
        heading: string;
        subheading?: string;
        image?: Media | string;
        ctaLabel?: string;
        ctaLink?: UrlField;
      }
    | {
        blockType: "features";
        heading?: string;
        items?: Array<{
          icon?: string;
          title: string;
          description?: string;
        }>;
      }
    | {
        blockType: "richContent";
        content: string;
      }
    | {
        blockType: "cta";
        heading: string;
        description?: string;
        buttonLabel?: string;
        buttonLink?: UrlField;
      }
    | {
        blockType: "pricing";
        heading?: string;
        plans?: Array<{
          name: string;
          price?: string;
          features?: Array<{
            text?: string;
          }>;
          ctaLabel?: string;
          ctaLink?: UrlField;
        }>;
      }
    | {
        blockType: "logos";
        heading?: string;
        items?: Array<{
          name?: string;
        }>;
      }
    | {
        blockType: "stats";
        items?: Array<{
          value: string;
          label: string;
        }>;
      }
    | {
        blockType: "team";
        heading?: string;
        members?: Array<{
          name: string;
          role?: string;
          bio?: string;
          initials?: string;
        }>;
      }
    | {
        blockType: "press";
        items?: Array<{
          publication: string;
          quote: string;
          date?: string;
        }>;
      }
    | {
        blockType: "faq";
        heading?: string;
        items?: Array<{
          question: string;
          answer: string;
        }>;
      }
    | {
        blockType: "testimonial";
        quote: string;
        author: string;
        role?: string;
        initials?: string;
      }
    | {
        blockType: "comparison";
        heading?: string;
        rows?: Array<{
          feature: string;
          snacktrack?: boolean;
          competitorA?: string;
          competitorB?: string;
        }>;
      }
    | {
        blockType: "timeline";
        items?: Array<{
          year: string;
          title: string;
          description?: string;
        }>;
      }
    | {
        blockType: "contactForm";
        heading?: string;
        subheading?: string;
      }
  >;
  createdAt: string;
  updatedAt: string;
}

export interface Blog {
  id: string;
  title: string;
  slug: string;
  content: string;
  featuredImage?: Media | string;
  author?: Authors | string;
  publishedDate?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Products {
  id: string;
  title: string;
  slug: string;
  description?: string;
  price?: number;
  image?: Media | string;
  featured?: boolean;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Authors {
  id: string;
  name: string;
  bio?: string;
  avatar?: Media | string;
  createdAt: string;
  updatedAt: string;
}

export interface SettingsGlobal {
  siteName?: string;
  tagline?: string;
  logo?: Media | string;
  footerText?: string;
}

export interface NavigationGlobal {
  navLinks?: Array<{
    title?: string;
    url?: UrlField;
  }>;
  ctaButton?: UrlField;
}

export interface DyrectedSchema {
  collections: {
    media: Media;
    pages: Pages;
    blog: Blog;
    products: Products;
    authors: Authors;
  };
  globals: {
    settings: SettingsGlobal;
    navigation: NavigationGlobal;
  };
}
