/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  focalPoint?: { x: number; y: number };
  blurhash?: string;
  sizes?: Record<
    string,
    { filename?: string; url?: string; width?: number; height?: number }
  >;
  createdAt: string;
  updatedAt: string;
}

// URL field types
export type UrlFieldValue =
  | {
      type: "custom";
      url: string;
      label?: string;
    }
  | {
      type: "internal";
      url: string;
      relationTo: string;
      value: string;
      label?: string;
    };

// Backward compatibility for simple string URLs
export type UrlField = UrlFieldValue | string;

export interface Users {
  id: string;
  name: string;
  role: "admin" | "editor";
  email: string;
  roles?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Testimonials {
  id: string;
  quote: string;
  author: string;
  title: string;
  avatar: string;
  order?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Values {
  id: string;
  icon: string;
  title: string;
  desc: string;
  order?: number;
  createdAt: string;
  updatedAt: string;
}

export interface FaqEntries {
  id: string;
  q: string;
  a: string;
  order?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Services {
  id: string;
  name: string;
  serviceId: string;
  description: string;
  price: string;
  duration: string;
  benefits?: Array<{
    text: string;
  }>;
  order?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Articles {
  id: string;
  title: string;
  slug: string;
  category: string;
  readTime: string;
  date: string;
  excerpt: string;
  content?: Array<{
    paragraph: string;
  }>;
  createdAt: string;
  updatedAt: string;
}

export interface NavGlobal {
  brandName: string;
  brandSubtitle?: string;
  links?: Array<{
    name: string;
    href: string;
  }>;
  dashboardLabel?: string;
  diagnosticLabel?: string;
}

export interface FooterGlobal {
  tagline?: string;
  newsletter?: {
    title?: string;
    description?: string;
    successMessage?: string;
  };
  disclaimer?: string;
}

export interface HomePageGlobal {
  hero?: {
    badge?: string;
    titlePrefix: string;
    titleHighlight: string;
    description?: string;
  };
  simulator?: {
    title?: string;
    titleHighlight?: string;
    description?: string;
    widgetLabel?: string;
    ranges?: Array<{
      maxVal: number;
      title: string;
      focus: string;
      finished: string;
      status: string;
      statusColor?: string;
      comment?: string;
    }>;
  };
  howItWorks?: {
    title?: string;
    titleHighlight?: string;
    description?: string;
    steps?: Array<{
      step: string;
      title: string;
      desc: string;
    }>;
  };
  featuredAssessment?: {
    badge?: string;
    title: string;
    description?: string;
  };
  testimonialsHeader?: {
    title?: string;
    titleHighlight?: string;
    description?: string;
  };
  finalCta?: {
    title?: string;
    description?: string;
  };
}

export interface AboutPageGlobal {
  hero?: {
    titlePrefix: string;
    titleHighlight: string;
    description?: string;
  };
  profile?: {
    badge?: string;
    name: string;
    title?: string;
    bioParagraph1: string;
    bioParagraph2?: string;
    specialization?: string;
    experience?: string;
  };
  valuesHeader?: {
    titlePrefix?: string;
    titleHighlight?: string;
    description?: string;
  };
  faqHeader?: {
    title?: string;
    description?: string;
  };
}

export interface ServicesPageGlobal {
  hero?: {
    badge?: string;
    titlePrefix: string;
    titleHighlight: string;
    description?: string;
  };
  warningCallout?: {
    title: string;
    description?: string;
    actionLabel: string;
  };
}

export interface AssessmentPageGlobal {
  badge?: string;
  questions?: Array<{
    text: string;
    comment: string;
  }>;
}

export interface AssessmentResultsPageGlobal {
  header?: {
    badge?: string;
    title?: string;
  };
  saveReport?: {
    title?: string;
    description?: string;
  };
  bookingCta?: {
    title?: string;
    description?: string;
  };
  categories?: {
    CONCERNED?: {
      title: string;
      summary: string;
      strengths?: Array<{
        text: string;
      }>;
      growthOpportunities?: Array<{
        text: string;
      }>;
      recommendation: string;
    };
    OPTIMISTIC?: {
      title: string;
      summary: string;
      strengths?: Array<{
        text: string;
      }>;
      growthOpportunities?: Array<{
        text: string;
      }>;
      recommendation: string;
    };
    PROUD?: {
      title: string;
      summary: string;
      strengths?: Array<{
        text: string;
      }>;
      growthOpportunities?: Array<{
        text: string;
      }>;
      recommendation: string;
    };
    BRAGGING?: {
      title: string;
      summary: string;
      strengths?: Array<{
        text: string;
      }>;
      growthOpportunities?: Array<{
        text: string;
      }>;
      recommendation: string;
    };
  };
}

export interface BlogPageGlobal {
  hero?: {
    badge?: string;
    titlePrefix: string;
    titleHighlight: string;
    description?: string;
  };
}

export interface BookingPageGlobal {
  serviceStep?: {
    title: string;
    description?: string;
  };
  intakeStep?: {
    title: string;
    description?: string;
  };
  scheduleStep?: {
    title: string;
    description?: string;
    dates?: Array<{
      label: string;
      desc: string;
    }>;
  };
  successStep?: {
    badge?: string;
    title: string;
    description: string;
    note?: string;
  };
}

export interface ContactPageGlobal {
  hero?: {
    badge?: string;
    titlePrefix: string;
    titleHighlight: string;
    description?: string;
  };
  channels?: Array<{
    icon?: string;
    title: string;
    detail: string;
    variant?: "primary" | "secondary" | "muted";
  }>;
  success?: {
    title?: string;
    description?: string;
  };
}

export interface DyrectedSchema {
  collections: {
    users: Users;
    testimonials: Testimonials;
    values: Values;
    "faq-entries": FaqEntries;
    services: Services;
    articles: Articles;
  };
  globals: {
    nav: NavGlobal;
    footer: FooterGlobal;
    "home-page": HomePageGlobal;
    "about-page": AboutPageGlobal;
    "services-page": ServicesPageGlobal;
    "assessment-page": AssessmentPageGlobal;
    "assessment-results-page": AssessmentResultsPageGlobal;
    "blog-page": BlogPageGlobal;
    "booking-page": BookingPageGlobal;
    "contact-page": ContactPageGlobal;
  };
}
