#!/usr/bin/env node
import { Command } from 'commander';
import prettier from 'prettier';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';

const program = new Command();

program
  .name('dyrected')
  .description('Dyrected CMS CLI tool')
  .version('0.0.1');

program
  .command('generate:types')
  .description('Generate TypeScript interfaces from your Dyrected schema')
  .option('-u, --url <url>', 'Base URL of your Dyrected API', 'http://localhost:3000')
  .option('-o, --output <path>', 'Output file path', './dyrected-types.ts')
  .action(async (options) => {
    try {
      console.log(chalk.blue(`Fetching schemas from ${options.url}/api/schemas...`));
      
      const response = await fetch(`${options.url}/api/schemas`);
      if (!response.ok) {
        throw new Error(`Failed to fetch schemas: ${response.statusText}`);
      }
      
      const schema = await response.json();
      const code = generateTypes(schema);
      
      const formattedCode = await prettier.format(code, { parser: 'typescript' });
      
      await fs.outputFile(path.resolve(process.cwd(), options.output), formattedCode);
      
      console.log(chalk.green(`\nSuccess! Types generated at ${options.output}`));
    } catch (error: any) {
      console.error(chalk.red(`\nError: ${error.message}`));
      process.exit(1);
    }
  });

function generateTypes(schema: any) {
  let code = `/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
\n`;

  // Collections
  for (const col of schema.collections) {
    const interfaceName = toPascalCase(col.slug);
    code += `export interface ${interfaceName} {\n`;
    code += `  id: string;\n`;
    
    for (const field of col.fields) {
      code += `  ${field.name}${field.required ? '' : '?'}: ${mapFieldType(field)};\n`;
    }
    
    code += `  createdAt: string;\n`;
    code += `  updatedAt: string;\n`;
    code += `}\n\n`;
  }

  // Globals
  for (const glb of schema.globals) {
    const interfaceName = `${toPascalCase(glb.slug)}Global`;
    code += `export interface ${interfaceName} {\n`;
    
    for (const field of glb.fields) {
      code += `  ${field.name}${field.required ? '' : '?'}: ${mapFieldType(field)};\n`;
    }
    
    code += `}\n\n`;
  }

  // Registry
  code += `export interface DyrectedSchema {\n`;
  code += `  collections: {\n`;
  for (const col of schema.collections) {
    code += `    ${col.slug}: ${toPascalCase(col.slug)};\n`;
  }
  code += `  };\n`;
  code += `  globals: {\n`;
  for (const glb of schema.globals) {
    code += `    ${glb.slug}: ${toPascalCase(glb.slug)}Global;\n`;
  }
  code += `  };\n`;
  code += `}\n`;

  return code;
}

function mapFieldType(field: any): string {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'richText':
    case 'date':
    case 'email':
    case 'url':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'select':
      return field.options ? field.options.map((o: any) => `'${typeof o === 'string' ? o : o.value}'`).join(' | ') : 'string';
    case 'relationship':
      return field.collection === 'media' ? 'Media | string' : `${toPascalCase(field.collection)} | string`;
    case 'array':
      return 'any[]'; // Deep nesting handled later
    case 'object':
      return 'any';
    default:
      return 'any';
  }
}

function toPascalCase(str: string) {
  return str.replace(/(^\w|-\w)/g, (m) => m.replace(/-/, '').toUpperCase());
}

program.parse();
