import prettier from "prettier";
import chalk from "chalk";
import fs from "fs-extra";
import path from "path";
import { createJiti } from "jiti";

function resolveFieldBlocks(field: any, registry: Map<string, any>): any {
  const next = { ...field };

  if (next.fields) {
    next.fields = next.fields.map((child: any) =>
      resolveFieldBlocks(child, registry),
    );
  }

  if (
    next.type === "blocks" &&
    Array.isArray(next.blockReferences) &&
    next.blockReferences.length > 0
  ) {
    next.blocks = next.blockReferences
      .map((slug: string) => registry.get(slug))
      .filter(Boolean)
      .map((block: any) => resolveBlock(block, registry));
    return next;
  }

  if (next.blocks) {
    next.blocks = next.blocks.map((block: any) =>
      resolveBlock(block, registry),
    );
  }

  return next;
}

function resolveBlock(block: any, registry: Map<string, any>): any {
  return {
    ...block,
    fields: (block.fields || []).map((field: any) =>
      resolveFieldBlocks(field, registry),
    ),
  };
}

function resolveSchemaBlocks(schema: any): any {
  const registry = new Map<string, any>(
    (schema.blocks || []).map(
      (block: any) => [block.slug, block] as [string, any],
    ),
  );
  return {
    ...schema,
    collections: (schema.collections || []).map((collection: any) => ({
      ...collection,
      fields: (collection.fields || []).map((field: any) =>
        resolveFieldBlocks(field, registry),
      ),
    })),
    globals: (schema.globals || []).map((global: any) => ({
      ...global,
      fields: (global.fields || []).map((field: any) =>
        resolveFieldBlocks(field, registry),
      ),
    })),
  };
}

export async function runGenerateTypes(options: {
  url?: string;
  config: string;
  output: string;
}) {
  let schema: any;

  if (options.url) {
    console.log(
      chalk.blue(`Fetching schemas from ${options.url}/api/schemas...`),
    );
    const response = await fetch(`${options.url}/api/schemas`);
    if (!response.ok)
      throw new Error(`Failed to fetch schemas: ${response.statusText}`);
    schema = await response.json();
  } else {
    const configPath = path.resolve(process.cwd(), options.config);
    if (await fs.pathExists(configPath)) {
      console.log(
        chalk.blue(`Generating types from local config: ${configPath}...`),
      );
      const jiti = createJiti(configPath);
      const configModule = (await jiti.import(configPath)) as any;
      schema = configModule.default || configModule;
    } else {
      const url = "http://localhost:3000";
      console.log(
        chalk.blue(
          `No local config found. Fetching schemas from ${url}/api/schemas...`,
        ),
      );
      const response = await fetch(`${url}/api/schemas`);
      if (!response.ok)
        throw new Error(`Failed to fetch schemas: ${response.statusText}`);
      schema = await response.json();
    }
  }

  if (!schema || !schema.collections)
    throw new Error("Invalid schema: collections missing.");

  const code = generateTypes(resolveSchemaBlocks(schema));
  const formattedCode = await prettier.format(code, { parser: "typescript" });
  await fs.outputFile(
    path.resolve(process.cwd(), options.output),
    formattedCode,
  );

  console.log(chalk.green(`✔  Types generated at ${options.output}`));
}

export function generateTypes(schema: any): string {
  let code = `/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  focalPoint?: { x: number; y: number };
  blurhash?: string;
  sizes?: Record<string, { filename?: string; url?: string; width?: number; height?: number }>;
  createdAt: string;
  updatedAt: string;
}

// URL field types
export type UrlFieldValue = {
  type: 'custom';
  url: string;
  label?: string;
} | {
  type: 'internal';
  url: string;
  relationTo: string;
  value: string;
  label?: string;
};

// Backward compatibility for simple string URLs
export type UrlField = UrlFieldValue | string;
\n`;

  for (const col of schema.collections) {
    if (!col || !col.slug) continue;
    const interfaceName = toPascalCase(col.slug);

    if (interfaceName === "Media") {
      const extraFields = col.fields.filter(
        (f: any) =>
          ![
            "filename",
            "filesize",
            "mimeType",
            "url",
            "width",
            "height",
            "focalPoint",
            "blurhash",
            "sizes",
            "createdAt",
            "updatedAt",
          ].includes(f.name),
      );
      if (extraFields.length > 0) {
        const mediaStart = code.indexOf("export interface Media {");
        const updatedAtIndex = code.indexOf("updatedAt: string;", mediaStart);
        const insertionPoint = code.indexOf("}", updatedAtIndex);
        const fieldsCode = extraFields
          .map(
            (f: any) =>
              `  ${f.name}${f.required ? "" : "?"}: ${mapFieldType(f)};`,
          )
          .join("\n");
        code =
          code.slice(0, insertionPoint) +
          fieldsCode +
          "\n" +
          code.slice(insertionPoint);
      }
      continue;
    }

    if (code.includes(`export interface ${interfaceName} {`)) continue;

    code += `export interface ${interfaceName} {\n`;
    code += `  id: string;\n`;
    const declaredFields = new Set<string>(["id"]);
    for (const field of col.fields) {
      if (!field.name || field.type === "join") continue;
      if (["createdAt", "updatedAt", "id"].includes(field.name)) continue;
      code += `  ${propertyName(field.name)}${field.required ? "" : "?"}: ${mapFieldType(field)};\n`;
      declaredFields.add(field.name);
    }
    if (col.auth) {
      // Auth collections gain `email` and `roles`, but only add them when the
      // schema didn't already declare a field of that name. Otherwise the
      // interface would carry the property twice with conflicting types (e.g. a
      // `roles` select field is `'admin' | 'editor'`, not `string[]`), which is
      // a TypeScript error. The schema's own definition wins.
      if (!declaredFields.has("email")) code += `  email: string;\n`;
      if (!declaredFields.has("roles")) code += `  roles?: string[];\n`;
    }
    if (col.upload) code += uploadFields();
    code += `  createdAt: string;\n`;
    code += `  updatedAt: string;\n`;
    code += `}\n\n`;
  }

  for (const glb of schema.globals) {
    if (!glb || !glb.slug) continue;
    const interfaceName = `${toPascalCase(glb.slug)}Global`;
    code += `export interface ${interfaceName} {\n`;
    for (const field of glb.fields) {
      if (!field.name || field.type === "join") continue;
      code += `  ${propertyName(field.name)}${field.required ? "" : "?"}: ${mapFieldType(field)};\n`;
    }
    code += `}\n\n`;
  }

  code += `export interface DyrectedSchema {\n`;
  code += `  collections: {\n`;
  for (const col of schema.collections) {
    code += `    ${propertyName(col.slug)}: ${toPascalCase(col.slug)};\n`;
  }
  code += `  };\n`;
  code += `  globals: {\n`;
  for (const glb of schema.globals) {
    code += `    ${propertyName(glb.slug)}: ${toPascalCase(glb.slug)}Global;\n`;
  }
  code += `  };\n`;
  code += `}\n`;

  // Register the schema globally with @dyrected/sdk. Once this file is part of
  // the compilation, the SDK client and every framework hook (React/Vue/Nuxt)
  // are typed against DyrectedSchema automatically — no per-call generics.
  code += `\n`;
  code += `declare module "@dyrected/sdk" {\n`;
  code += `  interface Register {\n`;
  code += `    schema: DyrectedSchema;\n`;
  code += `  }\n`;
  code += `}\n`;

  return code;
}

/**
 * Build a union of string literals from a select/radio/multiSelect field's
 * `options` (accepting both `"value"` and `{ label, value }` shapes). Returns
 * `null` when there are no options to enumerate.
 */
function optionsUnion(options: any): string | null {
  if (!Array.isArray(options) || options.length === 0) return null;
  return options
    .map((o: any) => JSON.stringify(typeof o === "string" ? o : o.value))
    .join(" | ");
}

export function mapFieldType(field: any): string {
  switch (field.type) {
    case "text":
    case "textarea":
    case "date":
    case "datetime":
    case "time":
    case "email":
    case "icon":
      return "string";
    case "richText":
    case "json":
      return "Record<string, unknown>";
    case "url":
      return "UrlField";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "select":
    case "radio": {
      const union = optionsUnion(field.options);
      return union ?? "string";
    }
    case "multiSelect": {
      // Emit an array of the option literals (an enum), not a loose string[],
      // so a multi-valued field like `roles` stays typed as its allowed values.
      const union = optionsUnion(field.options);
      return union ? `(${union})[]` : "string[]";
    }
    case "image":
    case "relationship": {
      const relationTo = field.relationTo || field.collection;
      const related =
        relationTo === "media"
          ? "Media | string"
          : `${toPascalCase(relationTo)} | string`;
      return field.hasMany ? `Array<${related}>` : related;
    }
    case "array":
      return field.fields
        ? `Array<{\n${field.fields
            .filter((f: any) => f.name)
            .map(
              (f: any) =>
                `      ${propertyName(f.name)}${f.required ? "" : "?"}: ${mapFieldType(f)};`,
            )
            .join("\n")}\n    }>`
        : "unknown[]";
    case "blocks":
      return field.blocks
        ? `Array<${field.blocks
            .map(
              (b: any) =>
                `{\n      blockType: ${JSON.stringify(b.slug)};\n${b.fields
                  .filter((f: any) => f.name)
                  .map(
                    (f: any) =>
                      `      ${propertyName(f.name)}${f.required ? "" : "?"}: ${mapFieldType(f)};`,
                  )
                  .join("\n")}\n    }`,
            )
            .join(" | ")}>`
        : "unknown[]";
    case "object":
      return field.fields
        ? `{\n${field.fields
            .filter((f: any) => f.name)
            .map(
              (f: any) =>
                `    ${propertyName(f.name)}${f.required ? "" : "?"}: ${mapFieldType(f)};`,
            )
            .join("\n")}\n  }`
        : "Record<string, unknown>";
    case "join":
      return "unknown[]";
    case "row":
      return field.fields
        ? `{\n${field.fields
            .filter((f: any) => f.name)
            .map(
              (f: any) =>
                `    ${propertyName(f.name)}${f.required ? "" : "?"}: ${mapFieldType(f)};`,
            )
            .join("\n")}\n  }`
        : "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)
    ? value
    : JSON.stringify(value);
}

function uploadFields(): string {
  return [
    "  filename: string;",
    "  filesize?: number;",
    "  mimeType: string;",
    "  url: string;",
    "  width?: number;",
    "  height?: number;",
    "  blurhash?: string;",
    "  sizes?: Record<string, { filename?: string; url?: string; width?: number; height?: number }>;",
    "",
  ].join("\n");
}

function toPascalCase(str: string): string {
  if (!str) return "Unknown";
  return str.replace(/(^\w|-\w)/g, (m) => m.replace(/-/, "").toUpperCase());
}
