import prettier from "prettier";
import chalk from "chalk";
import fs from "fs-extra";
import path from "path";
import { createJiti } from "jiti";

export async function runGenerateTypes(options: { url?: string; config: string; output: string }) {
  let schema: any;

  if (options.url) {
    console.log(chalk.blue(`Fetching schemas from ${options.url}/api/schemas...`));
    const response = await fetch(`${options.url}/api/schemas`);
    if (!response.ok) throw new Error(`Failed to fetch schemas: ${response.statusText}`);
    schema = await response.json();
  } else {
    const configPath = path.resolve(process.cwd(), options.config);
    if (await fs.pathExists(configPath)) {
      console.log(chalk.blue(`Generating types from local config: ${configPath}...`));
      const jiti = createJiti(configPath);
      const configModule = (await jiti.import(configPath)) as any;
      schema = configModule.default || configModule;
    } else {
      const url = "http://localhost:3000";
      console.log(chalk.blue(`No local config found. Fetching schemas from ${url}/api/schemas...`));
      const response = await fetch(`${url}/api/schemas`);
      if (!response.ok) throw new Error(`Failed to fetch schemas: ${response.statusText}`);
      schema = await response.json();
    }
  }

  if (!schema || !schema.collections) throw new Error("Invalid schema: collections missing.");

  const code = generateTypes(schema);
  const formattedCode = await prettier.format(code, { parser: "typescript" });
  await fs.outputFile(path.resolve(process.cwd(), options.output), formattedCode);

  console.log(chalk.green(`✔  Types generated at ${options.output}`));
}

function generateTypes(schema: any): string {
  let code = `/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
\n`;

  for (const col of schema.collections) {
    if (!col || !col.slug) continue;
    const interfaceName = toPascalCase(col.slug);

    if (interfaceName === "Media") {
      const extraFields = col.fields.filter(
        (f: any) =>
          !["filename", "filesize", "mimeType", "url", "width", "height", "createdAt", "updatedAt"].includes(f.name),
      );
      if (extraFields.length > 0) {
        const insertionPoint = code.indexOf("}", code.indexOf("export interface Media {"));
        const fieldsCode = extraFields
          .map((f: any) => `  ${f.name}${f.required ? "" : "?"}: ${mapFieldType(f)};`)
          .join("\n");
        code = code.slice(0, insertionPoint) + fieldsCode + "\n" + code.slice(insertionPoint);
      }
      continue;
    }

    if (code.includes(`export interface ${interfaceName} {`)) continue;

    code += `export interface ${interfaceName} {\n`;
    code += `  id: string;\n`;
    for (const field of col.fields) {
      if (["createdAt", "updatedAt", "id"].includes(field.name)) continue;
      code += `  ${field.name}${field.required ? "" : "?"}: ${mapFieldType(field)};\n`;
    }
    code += `  createdAt: string;\n`;
    code += `  updatedAt: string;\n`;
    code += `}\n\n`;
  }

  for (const glb of schema.globals) {
    if (!glb || !glb.slug) continue;
    const interfaceName = `${toPascalCase(glb.slug)}Global`;
    code += `export interface ${interfaceName} {\n`;
    for (const field of glb.fields) {
      code += `  ${field.name}${field.required ? "" : "?"}: ${mapFieldType(field)};\n`;
    }
    code += `}\n\n`;
  }

  code += `export interface DyrectedSchema {\n`;
  code += `  collections: {\n`;
  for (const col of schema.collections) {
    code += `    ${col.slug}: ${toPascalCase(col.slug)};\n`;
  }
  code += `  };\n`;
  code += `  globals: {\n`;
  for (const glb of schema.globals) {
    code += `    ${glb.slug}: ${toPascalCase(glb.slug)}Global;\n`;
  }
  code += `  };\n`;
  code += `}\n`;

  return code;
}

function mapFieldType(field: any): string {
  switch (field.type) {
    case "text":
    case "textarea":
    case "richText":
    case "date":
    case "email":
    case "url":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "select":
      return field.options
        ? field.options.map((o: any) => `'${typeof o === "string" ? o : o.value}'`).join(" | ")
        : "string";
    case "relationship": {
      const relationTo = field.relationTo || field.collection;
      return relationTo === "media" ? "Media | string" : `${toPascalCase(relationTo)} | string`;
    }
    case "array":
      return field.fields
        ? `Array<{\n${field.fields.map((f: any) => `      ${f.name}${f.required ? "" : "?"}: ${mapFieldType(f)};`).join("\n")}\n    }>`
        : "any[]";
    case "blocks":
      return field.blocks
        ? `Array<${field.blocks.map((b: any) => `{\n      blockType: '${b.slug}';\n${b.fields.map((f: any) => `      ${f.name}${f.required ? "" : "?"}: ${mapFieldType(f)};`).join("\n")}\n    }`).join(" | ")}>`
        : "any[]";
    case "object":
      return field.fields
        ? `{\n${field.fields.map((f: any) => `    ${f.name}${f.required ? "" : "?"}: ${mapFieldType(f)};`).join("\n")}\n  }`
        : "any";
    default:
      return "any";
  }
}

function toPascalCase(str: string): string {
  if (!str) return "Unknown";
  return str.replace(/(^\w|-\w)/g, (m) => m.replace(/-/, "").toUpperCase());
}
